name: CI

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type checking
        run: npm run typecheck
        
      - name: Run tests with coverage
        run: npm run test > test-output.log 2>&1
        
      - name: Show test output
        run: cat test-output.log
        
      - name: Check 100% coverage
        run: |
          # Extract coverage percentage from test output
          COVERAGE=$(grep "all files" test-output.log | grep -o '[0-9]\+\.[0-9]\+' | head -1)
          echo "Coverage: $COVERAGE%"
          if [ -z "$COVERAGE" ]; then
            echo "Error: Could not parse coverage from output"
            cat test-output.log
            exit 1
          fi
          if [ $(echo "$COVERAGE < 100" | awk '{print ($1 < $3)}') -eq 1 ]; then
            echo "Error: Test coverage is $COVERAGE%, but 100% is required"
            exit 1
          fi
          echo "✓ 100% test coverage achieved"